export const text = {
  formTitle: 'טופס איכות הסביבה',
  goodsFormTitle: 'פרטי הטובין',
  userDetailsTitle: 'פרטי המבקש',
  contactorName: 'שם איש קשר',
  itemName: 'שם הפריט',
  category: 'בחר/י קטגוריה',
  itemPorpuse: 'ייעוד הפריט',
  requiredAmount: 'כמות מבוקשת בק"ג',
  supplierDetails: 'פרטי הספק',
  supplierName: 'שם הספק',
  chooseSource: 'בחר/י מקור טובין',
  goodsSource: 'מקור הטובין',
  businessID: 'מספר ח"פ',
  fullName: 'שם מלא',
  originatedCountry: 'מדינת מקור',
  materialsInfo: 'פרטי החומרים',
  ID: 'ת"ז',
  email: 'כתובת דוא"ל',
  mobileNumber: 'מספר טלפון נייד',
  phoneNumber: 'מספר טלפון',
  faxNumber: 'מספר פקס (אופצוינלי)',
  nextBtn: 'המשך',
  previousBtn: 'חזרה',
  ingredientsList: 'רשימת מרכיבים',
  itemDetails: 'פריט',
  addItemTitle: 'הוספת מרכיב לפי שם, פורמולה או מספר CAS',
  chooseResult: 'הקלידו כדי לחפש ובחרו מהתוצאות המוצעות',
  confirm: 'אישור',
  edit: 'עריכה',
};
